language: node_js
node_js:
  - 8
  - 9
install: npm install
script: bash ./travis/test.sh
jobs:
  include:
    - stage: deploy
      node_js: 9
      script: bash ./travis/deploy.sh
      env:
        - ENCRYPTION_LABEL="fcdb45ae398e"
        - COMMIT_AUTHOR_EMAIL="tony.langhammer@yahoo.de"
cache:
  directories:
    - node_modules
dist: trusty
sudo: false